name: WebAge Solutions Simple CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set Secret as Environment Variable
        run: echo "SECRET_VALUE=${{ secrets.YOUR_SECRET }}" >> $GITHUB_ENV

      - name: Print Secret
        run: echo $SECRET_VALUE
