name: Print Secret Example

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Set Secret as Environment Variable
        run: echo "SECRET_VALUE=${{ secrets.FIRSTNAME }}" >> $GITHUB_ENV

      - name: Print Secret
        run: echo $SECRET_VALUE

  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret for Debugging
        run: echo "Secret Value: ${{ secrets.FIRSTNAME }}"
